/*
 * embedded_packages.c - registry of packages compiled into the kernel
 *
 * See pkg/embedded_packages.h for the full "how to add a package"
 * workflow. This file is deliberately tiny and free of any real
 * logic (no parsing, no VFS calls, nothing that could break) --
 * it's a lookup table and two trivial accessors, so that adding an
 * entry here is a purely mechanical, low-risk edit even for someone
 * who has never touched the rest of vpkg's implementation.
 */

#include "pkg/embedded_packages.h"

/* Each embedded package's raw bytes + length, generated by
 * tools/bin2c.py from a real .vpk archive built by
 * tools/vpkbuild.py. See pkg/embedded_packages.h step 4 for how a
 * new package's extern line + registry entry gets added below. */
extern const u8 g_pkg_hello_vulcan[];
extern const usize g_pkg_hello_vulcan_size;

static const struct embedded_package registry[] = {
    { "hello-vulcan", g_pkg_hello_vulcan, 0 /* filled in at startup, see
                                              * embedded_packages_init below --
                                              * a global array initializer
                                              * cannot reference another
                                              * translation unit's variable
                                              * (g_pkg_hello_vulcan_size) as
                                              * a compile-time constant, only
                                              * as a runtime value */
    },
};

#define REGISTRY_COUNT (sizeof(registry) / sizeof(registry[0]))

/* Since C's static initializers can't reference another translation
 * unit's non-constant symbol (g_pkg_hello_vulcan_size), the `size`
 * fields above are patched in once at startup rather than at
 * compile time. embedded_packages_find/count/at all call this
 * first, so callers never observe an unpatched (zero) size --
 * cheap enough (REGISTRY_COUNT is small) to just re-run on every
 * call rather than adding a separate explicit init step callers
 * would need to remember to invoke first. */
static void ensure_sizes_patched(void)
{
    static bool patched = false;
    if (patched) {
        return;
    }
    /* Cast away const deliberately, ONLY for this one-time patch --
     * every other access to this array treats it as read-only,
     * matching its actual usage pattern everywhere else. */
    ((struct embedded_package *)&registry[0])->size = g_pkg_hello_vulcan_size;
    patched = true;
}

const struct embedded_package *embedded_package_find(const char *install_name)
{
    ensure_sizes_patched();

    for (usize i = 0; i < REGISTRY_COUNT; i++) {
        const char *a = registry[i].install_name;
        const char *b = install_name;
        while (*a && *a == *b) {
            a++;
            b++;
        }
        if (*a == *b) {
            return &registry[i];
        }
    }
    return NULL;
}

u32 embedded_package_count(void)
{
    return (u32)REGISTRY_COUNT;
}

const struct embedded_package *embedded_package_at(u32 index)
{
    ensure_sizes_patched();

    if (index >= REGISTRY_COUNT) {
        return NULL;
    }
    return &registry[index];
}
