#!/usr/bin/env python3
"""
bin2c.py - Converts a binary file into a compilable C source file

Usage:
    python3 bin2c.py <input.bin> <output.c> <variable_name>

Generates <output.c> containing:
    const u8 <variable_name>[] = { 0x.., 0x.., ... };
    const usize <variable_name>_size = <N>;

Used to turn a built .vpk archive (see vpkbuild.py) into something
that compiles directly into the VulcanOS kernel image -- see
kernel/include/pkg/embedded_packages.h for why this is currently
package installation's only transport, and exactly how the generated
file gets wired into vpkg's registry (two lines in
kernel/pkg/embedded_packages.c: one extern declaration, one registry
entry).

HOST-SIDE tool, same as vpkbuild.py -- runs when building VulcanOS,
not on VulcanOS itself.
"""

import sys
from pathlib import Path

BYTES_PER_LINE = 16


def bin2c(input_path: Path, output_path: Path, var_name: str) -> None:
    data = input_path.read_bytes()

    lines = []
    lines.append(
        "/* Auto-generated by tools/bin2c.py from "
        f"{input_path.name} -- do not edit by hand. */"
    )
    lines.append('#include "types.h"')
    lines.append("")
    lines.append(f"const u8 {var_name}[] = {{")

    for i in range(0, len(data), BYTES_PER_LINE):
        chunk = data[i : i + BYTES_PER_LINE]
        hex_bytes = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"    {hex_bytes},")

    lines.append("};")
    lines.append("")
    lines.append(f"const usize {var_name}_size = {len(data)};")
    lines.append("")

    output_path.write_text("\n".join(lines))
    print(f"generated {output_path} ({len(data)} bytes -> {var_name})")


def main() -> None:
    if len(sys.argv) != 4:
        sys.exit(__doc__)

    input_path = Path(sys.argv[1])
    output_path = Path(sys.argv[2])
    var_name = sys.argv[3]

    if not input_path.is_file():
        sys.exit(f"error: {input_path} is not a file")

    if not var_name.isidentifier():
        sys.exit(f"error: '{var_name}' is not a valid C identifier")

    bin2c(input_path, output_path, var_name)


if __name__ == "__main__":
    main()
